description: "A new Flutter application."
name: "flutterapp"
publish_to: "none"
version: "1.0.0+1"
dependencies: 
  modal_progress_hud_nsn: ^0.3.0
  # cupertino_icons: "^1.0.5"
  path_drawing: "^1.0.0"
  flutter: 
    sdk: "flutter"
  speech_to_text: ^6.0.0  
  firebase_auth: ^4.2.7
  firebase_core: ^2.5.0
  cloud_firestore: ^4.3.2
  video_player: ^2.6.0
  image_picker: ^0.8.7
  get: ^4.6.5
  jitsi_meet: ^4.0.0
  # tflite: ^1.1.2
  # tflite_flutter: ^0.9.4
  camera: ^0.10.4
  flutter_tts: ^3.6.3
  # speech_recognition: ^0.3.0+1 
dev_dependencies: 
  flutter_test: 
    sdk: "flutter"
environment: 
  sdk: ">=2.12.0 <3.0.0"
flutter: 
  assets: 
    - "assets/images/"
  fonts: 
    - 
      family: "Inter"
      fonts: 
        - 
          asset: "fonts/Inter-700.ttf"
          style: "normal"
          weight: 700
        - 
          asset: "fonts/Inter-900.ttf"
          style: "normal"
          weight: 900
        - 
          asset: "fonts/Inter-500.ttf"
          style: "normal"
          weight: 500
    - 
      family: "Aladin"
      fonts: 
        - 
          asset: "fonts/Aladin-regular.ttf"
          style: "normal"
          weight: 400
    - 
      family: "Roboto"
      fonts: 
        - 
          asset: "fonts/Roboto-500.ttf"
          style: "normal"
          weight: 500
        - 
          asset: "fonts/Roboto-300.ttf"
          style: "normal"
          weight: 300
        - 
          asset: "fonts/Roboto-regular.ttf"
          style: "normal"
          weight: 400
    - 
      family: "Poppins"
      fonts: 
        - 
          asset: "fonts/Poppins-600.ttf"
          style: "normal"
          weight: 600
    - 
      family: "Noto Sans"
      fonts: 
        - 
          asset: "fonts/NotoSans-regular.ttf"
          style: "normal"
          weight: 400
    - 
      family: "Merriweather"
      fonts: 
        - 
          asset: "fonts/Merriweather-700.ttf"
          style: "normal"
          weight: 700
  uses-material-design: true
