import 'package:flutter/material.dart';
import 'package:flutterapp/easy_20meetapp/generatedsplashwidget/generated/GeneratedWhatsApp_Image_20230424_at_8031Widget.dart';
import 'package:flutterapp/easy_20meetapp/generatedsplashwidget/generated/GeneratedEasyMeetWidget.dart';

/* Frame splash
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedSplashWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: GestureDetector(
      onTap: () => Navigator.pushNamed(context, '/SignUp'),
      child: ClipRRect(
        borderRadius: BorderRadius.zero,
        child: Container(
          width: 412.0,
          height: 850.0,
          child: Stack(
              fit: StackFit.expand,
              alignment: Alignment.center,
             // overflow: Overflow.visible,
              children: [
                ClipRRect(
                  borderRadius: BorderRadius.zero,
                  child: Container(
                    color: Color.fromARGB(255, 97, 29, 139),
                  ),
                ),
                Positioned(
                  left: 96.0,
                  top: 314.0,
                  right: null,
                  bottom: null,
                  width: 200.0,
                  height: 111.8541030883789,
                  child: GeneratedWhatsApp_Image_20230424_at_8031Widget(),
                ),
                Positioned(
                  left: 110.0,
                  top: 400.0,
                  right: null,
                  bottom: null,
                  width: 205.0,
                  height: 105.0,
                  child: GeneratedEasyMeetWidget(),
                )
              ]),
        ),
      ),
    ));
  }
}
